---
title: "Notes on Tidy Data"
author: "GW Dean"
date: "`r Sys.Date()`"
output: github_document
---
This document is written to help me understand the contents in Hadley Wickham's 2014 paper "Tidy Data" from the _Journal of Statistical Software_. It is intended to be an informal summary/commentary that will help me get at the main essence of the work. In addition, it will serve as a way to practice using RStudio and Github as a preparation for my upcoming presentation at UMass Dartmouth.

## High Level Overview of the Document
The first step in understanding a paper such as this is to gain a high-level overview of the structure of the document. The version I have can be found at the following link:

https://vita.had.co.nz/papers/tidy-data.pdf

Looks like a final pre-print, as there is no date listed. The website for the _Journal of Statistical Software_ can be found here:

https://www.jstatsoft.org/index

The document itself is 22 pages long, with an additional page of 15 references. The paper consists of an abstract, and seven sections. The seventh section is simply an acknowledgment of the people that Wickham worked with while developing the ideas in the paper, so the core of the paper is the first six sections, which we we list here:

1. Introduction (1-2)
2. Defining tidy data (2-5)
3. Tidying messy data sets (5-13)
4. Tidy tools (13-16)
5. Case Study (16-20)
6. Discussion (20-22)

Below I will boil each of these sections down as far as I can to extract the key points.

At the end of the Introduction section, Wickham summarizes the rest of the paper briefly as follows:

- **Section 2** defines the three characteristics that make a dataset tidy.

- **Section 3** describes the operations needed to make messy datasets tidy, and illustrates the techniques with a range of real examples.

- **Section 4** defines tidy tools, tools that input and output tidy datasets, and discusses how tidy data and tidy tools together can make data analysis easier.

- **Section 5** illustrates the tidy principles with a small case study.

- **Section 6** concludes with a discussion of what the framework misses and what other approaches might be fruitful to pursue.

## Introduction
"It is often said that 80% of data analysis is spent on the process of cleaning and preparing the data."

Data preparation must be repeated many times over the course of an analysis as new problems emerge.

This paper focuses on a small part of data cleaning called **tidying**: structuring datasets to facilitate analysis.

The principles of tidy data provide a standard way to organize data values within a dataset.

The principles of tidy data are closely related to those of relational databases and EF Codd's relational algebra. 

The principles described in this paper derived from the author's real-world data experience and developing numerous R packages to make dealing with messy datasets easier. From this experience emerged a comprehensive "philosophy of data" that underlies what has come to be called the **Tidyverse**.

<<<<<<< HEAD
=======


>>>>>>> d3daba520217c7131743a371293358c21e0c786c

## Defining tidy data

## Tidying messy data sets

## Tidy tools

## Case Study

## Discussion
